### ISSUE TITLE
Implement `configure` command

### ISSUE THREAD

**Issue by mih-kopylov** [mih-kopylov/bulker#155]
The command is to be used as a fluent bulker configuration tool.
Instead of creating a `bulker.yaml` file manually, it will create it with provided settings.

Usage:
```shell
bulker configure --debug --settings=/root/.bulker/settings.yaml --repos-directory=/root/projects/all --run-mode=par --max-workers=10 --no-progress=false --output=table
```

Assuming current user is `root`, it will generate a `/root/.bulker/bulker.yaml` file with content:
```yaml
debug: false
settingsFileName: /root/.bulker/settings.yaml
reposDirectory: /root/projects/all
runMode: par
maxWorkers: 10
noProgress: false
output: table
```
